# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import builder_pb2 as builder__pb2


class BuilderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildEnvironment = channel.unary_unary(
                '/Builder/BuildEnvironment',
                request_serializer=builder__pb2.BuildEnvironmentRequest.SerializeToString,
                response_deserializer=builder__pb2.BuildEnvironmentResponse.FromString,
                )


class BuilderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuildEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuilderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildEnvironment,
                    request_deserializer=builder__pb2.BuildEnvironmentRequest.FromString,
                    response_serializer=builder__pb2.BuildEnvironmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Builder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Builder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuildEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Builder/BuildEnvironment',
            builder__pb2.BuildEnvironmentRequest.SerializeToString,
            builder__pb2.BuildEnvironmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
